### ISSUE TITLE
Using Levenshtein distance to reduce data inconsistencies

### ISSUE THREAD

**Issue by coverprice** [Kalli/EssentialMixStats#2]
I noticed some inconsistencies in the original data, which may affect statistics. For example, `Y-Traxx` and `Y Traxx` are considered different artists, and so in the Most Played Tracks section, there are 2 separate totals for the same track "Mystery Land" (7 and 6 respectively) which should actually be combined.

To try and normalize these, I created a simple script which attempts to find similar artist names by removing punctuation, whitespace, and diacritics, and then looking for other artist names with a Levenshtein distance <= 2. [output & source](https://gist.github.com/coverprice/1b2ba774d52976437afa338293239432)

The output is very raw... and it needs to be curated by hand; there are many false positives hiding in the data.

Difference | Example
-- | --
Obviously all the same artist | `{'Loco Dice', 'Locodice', 'Locadice'}`
Mostly different artists, but with some that are the same | `{'Festa', 'Teste', 'TET', 'Tiësto', 'Tiesto'}`
Clearly different artists | `{'Unit 2', 'Unit 46'}`

I hope you can adapt my sample code and use the output to pre-process the data so that the totals are more accurate.

Thanks for doing this work, it's really interesting!

**Comment by Kalli** [comment]
hey Coverprice. Thanks for the issue, for looking into this and for the code. I will take a better look when I have some time, but looks good.  I had a go at some normalizing but was afraid I'd end up with more false positives than it would fix. It seems like your code is a bit more robust though, and maybe it just calls for curation afterwards like you say. 

Will look into it. Thanks again!

Side note, some of the false positives are pretty amusing 😄 

>Similar names:
>{'Skudge', 'Pudge'} [...]
>{'Todd Terje', 'Todd Terry'}

**Comment by Kalli** [comment]
Closing this as #3 has been merged.
